#!/bin/sh -e
# /usr/lib/emacsen-common/packages/remove/youtube-dl-el

FLAVOR=$1
PACKAGE=youtute-dl-el

#if test -x /usr/sbin/install-info-altdir; then
#    echo remove/${PACKAGE}: removing Info links for ${FLAVOR}
#    install-info-altdir --quiet --remove --dirname=${FLAVOR} /usr/info/${PACKAGE}.info.gz
#fi

echo remove/${PACKAGE}: purging byte-compiled files for ${FLAVOR}

if [ ${FLAVOR} = emacs ]; then
    rm -f /usr/share/${FLAVOR}/site-lisp/${PACKAGE}/*.elc
    rm -f /usr/share/${FLAVOR}/site-lisp/${PACKAGE}/youtube-dl-loaddefs.el
else rm -rf /usr/share/${FLAVOR}/site-lisp/${PACKAGE}
fi
